# Artificial Neural Network

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
df = pd.read_csv('/content/drive/My Drive/Data/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [6]:
print(df.iloc[:, :-1].values)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:

print(df.iloc[:, -1].values)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
df['Gender']= np.where(df['Gender']=='Female', 0, 1)
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncode()
# X = df.iloc[:, :-1].values
# X[:, 2] = le.fit_transform(X[:, 2])

One Hot Encoding the "Geography" column

In [9]:
df = pd.concat([pd.get_dummies(df['Geography']), df], axis=1)
df.drop('Geography', axis=1, inplace=True)
df.head()
# from sklearn.compose imoprt ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# X = df.iloc[:, :-1].values
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

France  Germany  Spain  ...  IsActiveMember  EstimatedSalary  Exited
0       1        0      0  ...               1        101348.88       1
1       0        0      1  ...               1        112542.58       0
2       1        0      0  ...               0        113931.57       1
3       1        0      0  ...               0         93826.63       0
4       0        0      1  ...               1         79084.10       0

[5 rows x 13 columns]

### Splitting the dataset into the Training set and Test set

In [10]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [11]:
print(X)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [12]:
print(y)

[1 0 1 ... 1 1 0]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [19]:
# try with 7 and check the accuracy
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# for non-binary classification, the activation function should be 'softmax'

## Part 3 - Training the ANN

### Compiling the ANN

In [22]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# for non-binary classification the loss function should be 'category_corossentropy'

### Training the ANN on the Training set

In [23]:
ann.fit(x=X_train, y=y_train, batch_size=32, epochs=100)
# batch_size = 32 is the default parameter - it is an important hyperparameter
# epoch is another important hyperparameter that should not be a small number
# because ann needs a certain amount of epochs to learn properly

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5781 - accuracy: 0.7628
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4916 - accuracy: 0.7950
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4559 - accuracy: 0.7956
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4386 - accuracy: 0.7995
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4281 - accuracy: 0.8052
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4165 - accuracy: 0.8156
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4041 - accuracy: 0.8241
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3927 - accuracy: 0.8320
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3821 - accuracy: 0.8379
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3729 - accura

## Part 4 - Making the predictions and evaluating the model

In [25]:
customer = [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]
customer = sc.transform(customer)
print(ann.predict(customer))

[[0.02374333]]


### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [27]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 206  199]]


0.8575